Added visualisations to the dashboard
clv1/plant-sensors-project pull request #31
Opened 2023-12-21 17:27 UTC by IshikaM19

I have created the dashboard :). 
I've added 2 separate script: The functions_for_database.py has all the functions that are used in dashboard.py. 
I've tried to create a bunch of different visualisations but I'm not sure If I have enough or if some of them are even relevant so please have a look and let me know. I also added all requirements to the requirements.txt :)

2023-12-21 21:27 UTC, clv1 commented on Dashboard/dashboard.py
> +    load_dotenv()
This might not be needed here - it looks like you're already calling load_dotenv() within the get_db_connection() function already.

2023-12-21 21:36 UTC, clv1 commented on Dashboard/dashboard.py
> +        ("All data", "Last 24 Hours")
Why the question mark? Maybe rephrase along the lines of "Select this box to view data for the past 24 hours:".

2023-12-21 21:37 UTC, clv1 commented on Dashboard/dashboard.py
> +    st.subheader('Moisture overtime', divider='rainbow')
"Moisture level over time"

2023-12-21 21:38 UTC, clv1 commented on Dashboard/dashboard.py
> +    st.subheader('The Diveristy of the plants based on Country')
"Diversity"

2023-12-21 21:39 UTC, clv1 commented on Dashboard/dashboard_functions.py
> +                ON s_alpha.origin_location.origin_location_id = s_alpha.plant.origin_location_id
Great point raised about the JOINs and nice implementation.

2023-12-21 21:40 UTC, clv1 commented on Dashboard/dashboard_functions.py
> +
spelling.

2023-12-21 21:41 UTC, clv1 commented on Dashboard/dashboard_functions.py
> +def make_temperature_graph(plants_data: pd.DataFrame, selected: list) -> alt.Chart:
Nice idea for a graph.

2023-12-21 21:48 UTC, clv1 requested changes
Changes requested are mostly just minor typos/spelling checks.
One thing worth discussing in our next huddle would be going over would be how we are implementing 24hrs/overall data.
Overall, dashboard code looks great and a really nice selection of graphs added!

2023-12-22 15:11 UTC, BenBeard115 approved these changes
Perfect!

2023-12-22 15:12 UTC, merged